name: Build C# Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Specify the .NET version you need

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: List files in current directory (debug code)
        run: ls -R
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            /home/runner/work/Integra7AuralAlchemist/Integra7AuralAlchemist/Src/bin/Release/net8.0/   # Adjust the path to your build output

#      - name: Run tests
#        run: dotnet test --configuration Release
